steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'release-$COMMIT_SHA'
    - '--delivery-pipeline=demo-pipeline'
    - '--region=us-central1'
    - '--images=demo-app=gcr.io/$PROJECT_ID/demo-app:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
